import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CopyPlus, Layers, Minus, Plus, Sparkles } from "lucide-react";
import * as pdfjsLib from "pdfjs-dist";
import pdfWorkerSrc from "pdfjs-dist/build/pdf.worker.min.mjs?url";
import type { PrintFile } from "@/lib/mock-data";

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfWorkerSrc as string;
const PORTRAIT = { width: 2480, height: 3508 };
const LANDSCAPE = { width: 3508, height: 2480 };
export type MultiLayoutState = { sourceFileIds: string[]; copies: Record<string, number>; rows: number; columns: number; orientation: "portrait" | "landscape"; gap: number; keepSources?: boolean };

async function loadImage(src: string) { return await new Promise<HTMLImageElement>((resolve,reject) => { const image=new Image(); image.crossOrigin="anonymous"; image.onload=()=>resolve(image); image.onerror=reject; image.src=src; }); }
async function filePages(file: PrintFile) {
  const source=file.workingSrc || file.src || file.livePreview; if (!source) return [];
  if (file.kind === "image") { const image=await loadImage(source); const canvas=document.createElement("canvas"); canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext("2d")!.drawImage(image,0,0);return [canvas]; }
  const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await (await fetch(source)).arrayBuffer())}).promise; const result:HTMLCanvasElement[]=[];
  for(let index=1;index<=pdf.numPages;index++){const page=await pdf.getPage(index);const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:3508/Math.max(base.width,base.height)});const canvas=document.createElement("canvas");canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);await page.render({canvas,canvasContext:canvas.getContext("2d")!,viewport}).promise;result.push(canvas);} return result;
}

export function MultiPageLayout({files,onGenerate,initialState,initialPreview}:{files:PrintFile[];onGenerate:(pages:string[],state:MultiLayoutState)=>Promise<void>;initialState?:MultiLayoutState;initialPreview?:string}){
  const usable=useMemo(()=>files.filter((item)=>item.src && !item.layoutType),[files]);
  const [selected,setSelected]=useState<string[]>(initialState?.sourceFileIds || []); const [copies,setCopies]=useState<Record<string,number>>(initialState?.copies || {});
  const [rows,setRows]=useState(initialState?.rows || 2),[columns,setColumns]=useState(initialState?.columns || 2); const [orientation,setOrientation]=useState<"portrait"|"landscape">(initialState?.orientation || "portrait");
  const [gap,setGap]=useState(initialState?.gap ?? 12),[keepSources,setKeepSources]=useState(initialState?.keepSources ?? true); const [previewPages,setPreviewPages]=useState<string[]>(initialPreview?[initialPreview]:[]),[previewIndex,setPreviewIndex]=useState(0); const [busy,setBusy]=useState(""),[error,setError]=useState("");
  const [step,setStep]=useState(initialState ? 3 : 0);
  const invalidate=()=>setPreviewPages([]); const toggle=(id:string)=>{setSelected((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);invalidate();};
  const setCopy=(id:string,value:number)=>{setCopies((current)=>({...current,[id]:Math.max(1,Math.min(20,value))}));invalidate();};
  const build=async()=>{if(!selected.length||busy)return;setBusy("Building 300 DPI preview...");setError("");try{const sources:HTMLCanvasElement[]=[];for(const id of selected){const file=usable.find((item)=>item.id===id);if(!file)continue;const pages=await filePages(file);for(let copy=0;copy<(copies[id]||1);copy++)sources.push(...pages);}const size=orientation==="portrait"?PORTRAIT:LANDSCAPE,perPage=rows*columns,output:string[]=[];for(let offset=0;offset<sources.length;offset+=perPage){const canvas=document.createElement("canvas");canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext("2d")!;ctx.fillStyle="white";ctx.fillRect(0,0,size.width,size.height);const density=300/96,margin=24*density,scaledGap=gap*density,boxW=(size.width-margin*2-scaledGap*(columns-1))/columns,boxH=(size.height-margin*2-scaledGap*(rows-1))/rows;sources.slice(offset,offset+perPage).forEach((source,index)=>{const col=index%columns,row=Math.floor(index/columns),x=margin+col*(boxW+scaledGap),y=margin+row*(boxH+scaledGap);ctx.drawImage(source,x,y,boxW,boxH);});output.push(canvas.toDataURL("image/jpeg",1));}setPreviewPages(output);setPreviewIndex(0);return output;}catch(reason){setError(reason instanceof Error?reason.message:"Layout preview failed");}finally{setBusy("");}};
  const generate=async()=>{if(!previewPages.length)return;setBusy(`Saving ${previewPages.length} pages...`);try{await onGenerate(previewPages,{sourceFileIds:selected,copies,rows,columns,orientation,gap,keepSources});}finally{setBusy("");}};
  const next=async()=>{if(step===2){const output=await build();if(output?.length)setStep(3);return;}setStep((value)=>Math.min(3,value+1));};
  const changeGrid=(r:number,c:number)=>{setRows(r);setColumns(c);invalidate();};
  return <div className="flex h-full min-h-0"><div className="min-w-0 flex-1 overflow-y-auto bg-muted/20 p-4">
    <div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-semibold">{step===0?"Select images and PDFs":step===1?"Order and copies":step===2?"Page settings":"Review generated pages"}</h3><p className="text-[10px] text-muted-foreground">{step===0?"Click files to include":step===1?"Drag selected cards and set repeat count":step===2?"Choose grid, orientation and spacing":"Nothing is added to Column 2 until Generate"}</p></div>{step===0&&<button onClick={()=>{setSelected(usable.map((item)=>item.id));invalidate();}} className="rounded border border-border px-2 py-1 text-[10px]">Select All</button>}</div>
    {step===3&&previewPages.length>0&&<div className="mb-4 rounded-lg border border-primary/40 bg-black/30 p-3"><div className="mb-2 flex text-[10px]"><b className="text-primary">LAYOUT PREVIEW — Page {previewIndex+1}/{previewPages.length}</b><span className="ml-auto text-muted-foreground">Review before Generate</span></div><img src={previewPages[previewIndex]} className="mx-auto max-h-[520px] max-w-full border border-white/30 object-contain shadow-xl" alt="Layout preview"/><div className="mt-2 flex justify-center gap-2"><button disabled={!previewIndex} onClick={()=>setPreviewIndex((i)=>i-1)} className="rounded border border-border px-3 py-1 text-[10px] disabled:opacity-30">Previous</button><button disabled={previewIndex===previewPages.length-1} onClick={()=>setPreviewIndex((i)=>i+1)} className="rounded border border-border px-3 py-1 text-[10px] disabled:opacity-30">Next</button></div></div>}
    {step<=1&&<div className="grid grid-cols-5 gap-2">{usable.map((item)=>{const active=selected.includes(item.id),count=copies[item.id]||1;return <div key={item.id} draggable={active&&step===1} onDragStart={(event)=>event.dataTransfer.setData("text/plain",item.id)} onDragOver={(event)=>active&&event.preventDefault()} onDrop={(event)=>{event.preventDefault();const from=event.dataTransfer.getData("text/plain");setSelected((current)=>{const next=current.filter((id)=>id!==from);next.splice(Math.max(0,next.indexOf(item.id)),0,from);return next;});invalidate();}} className={`overflow-hidden rounded border ${active?"border-primary bg-primary/10":"border-border bg-card"}`}><button onClick={()=>step===0&&toggle(item.id)} className="block w-full"><div className="flex aspect-square items-center justify-center bg-black/20">{item.kind==="image"?<img src={item.livePreview||item.workingSrc||item.src} className="h-full w-full object-contain" alt=""/>:<span className="text-xs font-bold text-rose-300">PDF<br/><small>{item.pages||"all"} pages</small></span>}</div><div className="truncate p-1 text-[9px]">{active?`${selected.indexOf(item.id)+1}. `:""}{item.name}</div></button>{active&&step===1&&<div className="flex items-center justify-center gap-1 border-t border-border p-1"><button onClick={()=>setCopy(item.id,count-1)}><Minus className="h-3 w-3"/></button><span className="min-w-7 text-center text-[9px]">× {count}</span><button onClick={()=>setCopy(item.id,count+1)}><Plus className="h-3 w-3"/></button></div>}</div>;})}</div>}
  </div><aside className="flex w-72 flex-col border-l border-border bg-card/50 p-3"><div className="flex items-center gap-2"><Layers className="h-4 w-4 text-primary"/><b className="text-xs">Multi Layout Wizard</b></div><div className="mt-3 grid grid-cols-4 gap-1">{["Select","Order","Page","Preview"].map((label,index)=><div key={label} className={`rounded px-1 py-1.5 text-center text-[8px] ${step===index?"bg-primary text-primary-foreground":index<step?"bg-primary/15 text-primary":"bg-accent/30 text-muted-foreground"}`}>{index+1}. {label}</div>)}</div>
    {step===2&&<><div className="mt-4 grid grid-cols-3 gap-2">{[[1,1,"1 in 1"],[1,2,"2 in 1"],[2,2,"4 in 1"]].map(([r,c,label])=><button key={label} onClick={()=>changeGrid(r as number,c as number)} className={`rounded border p-2 text-[10px] ${rows===r&&columns===c?"border-primary bg-primary/10":"border-border"}`}>{label}</button>)}</div>
    <label className="mt-4 text-[10px]">Custom Rows<input type="number" min="1" max="6" value={rows} onChange={(e)=>changeGrid(Math.max(1,Math.min(6,+e.target.value)),columns)} className="mt-1 w-full rounded border border-border bg-background p-1.5"/></label><label className="mt-2 text-[10px]">Custom Columns<input type="number" min="1" max="6" value={columns} onChange={(e)=>changeGrid(rows,Math.max(1,Math.min(6,+e.target.value)))} className="mt-1 w-full rounded border border-border bg-background p-1.5"/></label>
    <label className="mt-2 text-[10px]">Page Orientation<select value={orientation} onChange={(e)=>{setOrientation(e.target.value as typeof orientation);invalidate();}} className="mt-1 w-full rounded border border-border bg-background p-1.5"><option value="portrait">A4 Portrait</option><option value="landscape">A4 Landscape</option></select></label><label className="mt-2 text-[10px]">Gap: {gap}px<input type="range" min="0" max="50" value={gap} onChange={(e)=>{setGap(+e.target.value);invalidate();}} className="w-full accent-cyan-500"/></label>
    <label className="mt-3 flex items-center justify-between rounded border border-border bg-background/50 p-2 text-[10px]"><span><b>Keep source single files</b><small className="block text-[9px] text-muted-foreground">Keep originals in Column 2</small></span><input type="checkbox" checked={keepSources} onChange={(e)=>setKeepSources(e.target.checked)} className="accent-cyan-500"/></label></>}<div className="mt-3 rounded bg-background/50 p-2 text-[10px]"><CopyPlus className="mr-1 inline h-3 w-3"/>{selected.length} files selected</div>
    <div className="mt-auto space-y-2">{error&&<p className="text-[10px] text-destructive">{error}</p>}<div className="flex gap-2"><button onClick={()=>setStep((value)=>Math.max(0,value-1))} disabled={step===0||!!busy} className="inline-flex items-center gap-1 rounded border border-border px-2 py-2 text-xs disabled:opacity-30"><ArrowLeft className="h-3 w-3"/>Back</button>{step<3?<button onClick={()=>void next()} disabled={!selected.length||!!busy} className="ml-auto inline-flex items-center gap-1 rounded bg-primary px-2 py-2 text-xs text-primary-foreground disabled:opacity-40">{busy||"Apply & Next"}<ArrowRight className="h-3 w-3"/></button>:<button onClick={()=>void generate()} disabled={!previewPages.length||!!busy} className="ml-auto flex items-center justify-center gap-1 rounded bg-primary px-2 py-2 text-xs text-primary-foreground disabled:opacity-40"><Sparkles className="h-3 w-3"/>Generate</button>}</div></div>
  </aside></div>;
}
